// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct ByteArraysCommand : IEntityCommand
    {
        public System.Byte[] bytes1;
        public System.Byte[] bytes2;
        public System.Byte[] bytes3;
        public System.Byte[] bytes4;
        public System.Byte[] bytes5;
        public System.Byte[] bytes6;
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 11;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public ByteArraysCommand(
            Entity entity,
            System.Byte[] bytes1,
            System.Byte[] bytes2,
            System.Byte[] bytes3,
            System.Byte[] bytes4,
            System.Byte[] bytes5,
            System.Byte[] bytes6
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.bytes1 = bytes1; 
            this.bytes2 = bytes2; 
            this.bytes3 = bytes3; 
            this.bytes4 = bytes4; 
            this.bytes5 = bytes5; 
            this.bytes6 = bytes6; 
        }
        
        public static void Serialize(ByteArraysCommand commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteBytes(commandData.bytes1);
            bitStream.WriteBytes(commandData.bytes2);
            bitStream.WriteBytes(commandData.bytes3);
            bitStream.WriteBytes(commandData.bytes4);
            bitStream.WriteBytes(commandData.bytes5);
            bitStream.WriteBytes(commandData.bytes6);
        }
        
        public static ByteArraysCommand Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var databytes1 = bitStream.ReadBytes();
            var databytes2 = bitStream.ReadBytes();
            var databytes3 = bitStream.ReadBytes();
            var databytes4 = bitStream.ReadBytes();
            var databytes5 = bitStream.ReadBytes();
            var databytes6 = bitStream.ReadBytes();
    
            return new ByteArraysCommand()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                bytes1 = databytes1,
                bytes2 = databytes2,
                bytes3 = databytes3,
                bytes4 = databytes4,
                bytes5 = databytes5,
                bytes6 = databytes6
            };   
        }
    }

}
