// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System;
    using UnityEngine;

    public struct QuaternionInput : IEntityInput, IEquatable<QuaternionInput>
    {
        public uint GetComponentType() => 3;

        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        private bool isRemoteInput;

        public Quaternion quaternionField;

        public QuaternionInput(
        Entity entity,
        long frame,
        Quaternion quaternionField,
        bool isRemoteInput)
        {
            this.Entity = entity;
            this.ChannelID = Coherence.ChannelID.Default;
            this.Routing = MessageTarget.All;
            this.SenderParticipant = 0;
            this.SenderClientID = default;
            this.Frame = frame;
            this.isRemoteInput = isRemoteInput;
            this.quaternionField = quaternionField;
        }

        public override string ToString()
        {
            return $"Entity: {Entity}, Frame: {Frame}, Inputs: [quaternionField:{quaternionField}]";
        }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }

        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() => default;

        public void NullEntityRefs(Entity entity) { }

        public bool Equals(QuaternionInput other)
        {
            return
                this.quaternionField == other.quaternionField;
        }

        public static void Serialize(QuaternionInput inputData, IOutProtocolBitStream bitStream)
        {
            var converted_quaternionField = inputData.quaternionField.ToCoreQuaternion();
            bitStream.WriteQuaternion(converted_quaternionField, 32);
        }

        public static QuaternionInput Deserialize(IInProtocolBitStream bitStream, Entity entity, long frame)
        {
            var converted_quaternionField = bitStream.ReadQuaternion(32);
            var dataquaternionField = converted_quaternionField.ToUnityQuaternion();

            return new QuaternionInput()
            {
                Entity = entity,
                Frame = frame,
                quaternionField = dataquaternionField,
                isRemoteInput = true
            };
        }
    }

}
