// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_176612e6395a4d779175c5084af29050 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_07839436183f4488a4ab27210d0e0759 : DeepPositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_1595157206837191602);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_1595157206837191602";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
            set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_1595157206837191602)coherenceComponent).position;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_1595157206837191602)coherenceComponent).positionSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_1595157206837191602)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.position = Value;
            }
            else
            {
                update.position = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.positionSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_1595157206837191602();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_e47132bbd60843428b4e971dab9c27ee : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).VelocityY;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).VelocityYSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.VelocityY = Value;
            }
            else
            {
                update.VelocityY = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.VelocityYSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_edb89633b02a4a309dec88c387363651 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).AnimationSpeed;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).AnimationSpeedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.AnimationSpeed = Value;
            }
            else
            {
                update.AnimationSpeed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.AnimationSpeedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_c3502e90da7944d49eff99942245cfd1 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).Jump;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).JumpSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Jump = Value;
            }
            else
            {
                update.Jump = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.JumpSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_4f0d8280f3084fc0a4953880f4658384 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).Grounded;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).GroundedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Grounded = Value;
            }
            else
            {
                update.Grounded = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.GroundedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_d3b70c3b9f5a479fb9118fc4846a697b : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390";
        public override uint FieldMask => 0b00000000000000000000000000010000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).FreeFallDuration;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent).FreeFallDurationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.FreeFallDuration = Value;
            }
            else
            {
                update.FreeFallDuration = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.FreeFallDurationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_3053908138361248390();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_83840047ea654f3abca1b99ceab5cde2 : DeepRotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_3909198552495372456);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_3909198552495372456";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
            set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_3909198552495372456)coherenceComponent).rotation;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_3909198552495372456)coherenceComponent).rotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_3909198552495372456)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.rotation = Value;
            }
            else
            {
                update.rotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.rotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_3909198552495372456();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f7dcb50d464e141bb85c5d72434e2f8c_d31a5ba7cd884af6b08b703dd1342a36 : DeepRotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f7dcb50d464e141bb85c5d72434e2f8c_6710452508646171906);
        public override string CoherenceComponentName => "_f7dcb50d464e141bb85c5d72434e2f8c_6710452508646171906";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
            set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f7dcb50d464e141bb85c5d72434e2f8c_6710452508646171906)coherenceComponent).rotation;

            var simFrame = ((_f7dcb50d464e141bb85c5d72434e2f8c_6710452508646171906)coherenceComponent).rotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f7dcb50d464e141bb85c5d72434e2f8c_6710452508646171906)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.rotation = Value;
            }
            else
            {
                update.rotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.rotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f7dcb50d464e141bb85c5d72434e2f8c_6710452508646171906();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_f7dcb50d464e141bb85c5d72434e2f8c : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_f7dcb50d464e141bb85c5d72434e2f8c>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["176612e6395a4d779175c5084af29050"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_176612e6395a4d779175c5084af29050(),
			["07839436183f4488a4ab27210d0e0759"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_07839436183f4488a4ab27210d0e0759(),
			["e47132bbd60843428b4e971dab9c27ee"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_e47132bbd60843428b4e971dab9c27ee(),
			["edb89633b02a4a309dec88c387363651"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_edb89633b02a4a309dec88c387363651(),
			["c3502e90da7944d49eff99942245cfd1"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_c3502e90da7944d49eff99942245cfd1(),
			["4f0d8280f3084fc0a4953880f4658384"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_4f0d8280f3084fc0a4953880f4658384(),
			["d3b70c3b9f5a479fb9118fc4846a697b"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_d3b70c3b9f5a479fb9118fc4846a697b(),
			["83840047ea654f3abca1b99ceab5cde2"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_83840047ea654f3abca1b99ceab5cde2(),
			["d31a5ba7cd884af6b08b703dd1342a36"] = new Binding_f7dcb50d464e141bb85c5d72434e2f8c_d31a5ba7cd884af6b08b703dd1342a36(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_f7dcb50d464e141bb85c5d72434e2f8c()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_f7dcb50d464e141bb85c5d72434e2f8c Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_f7dcb50d464e141bb85c5d72434e2f8c>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
